language: ruby
rvm: 2.2.3
env: RAILS_ENV=test
script:
  - bundle exec rspec
addons:
  postgresql: "9.3"
before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
install: bundle install --jobs=3 --retry=3
services:
  - redis-server
